org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties (from fabric-example-mod branch 26.3, checked 2026-09-26)
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
version=0.1.0
group=io.github.plrlr.autopilot

# Dependencies
fabric_api_version=0.161.0+26.3
baritone_version=1.20.0
